In [3]:
from colorama import Fore, Back, Style 

In [4]:
import os
import nltk
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
import re
import sys
first_dictionary = {}
nested_dict = {}



# def read_tags(words_dir):
#     files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

#     # features_matrix = np.zeros((len(files), 3000))
#     docID = 0;
#     tagss = {}
#     for fil in files:
#         docID+=1
#         with open(fil) as fi:
#             for i, line in enumerate(fi):
#                 temp = line.split(',')
#                 print(temp)
#                 for k in temp:
#                     if k.lower() in tagss:
#                         tagss[k.lower()]=1
#                     else:
#                         tagss[k.lower()] = 1
#     return docID, tagss

#  search continuous keyword

def cnd(w, nested_dict):
#     print(w)
    if(len(w) == 0):
        return
    elif w[0].lower() not in nested_dict:
        nested_dict[w[0].lower()] = {}
        cnd(w[1:],nested_dict[w[0].lower()])
    else:
        cnd(w[1:],nested_dict[w[0].lower()])
    return


def read_tags(words_dir, nested_dict):
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil in files:
        docID+=1
        with open(fil) as fi:
            for line_number, line in enumerate(fi):
                temp = line.split(',')
#                 print(temp)
                for word in temp:
#                     word = re.sub('[^A-Za-z0-9]+', '', word)
#                     word = re.sub(r'^\s+', ' ',   word)
                    word = word.rstrip()
                    word = word.lstrip()
#                     print(word)
                    cnd(word.lower().split(), nested_dict)
    return docID, tagss

# read the db and creates dictionary
doc_id, tags = read_tags('tags', nested_dict)        


for i in tags:
    w = i.split()
    if(len(w) == 0):
        continue
    elif w[0].lower() in first_dictionary:
        first_dictionary[w[0].lower()].append(i)
    else:
        first_dictionary[w[0].lower()] = []
        first_dictionary[w[0].lower()].append(i)
        

        
# def create_nested_dict(tags, nested_dict):
#     for k, v in tags.items():
#         w = k.split()
#         cnd(w,nested_dict)
        

# create_nested_dict(tags, nested_dict)

In [26]:
import os
import nltk
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
import re
import sys
nested_dict = {}
def cnd(w, nested_dict):
#     print(w)
    if(len(w) == 0):
        return
    elif w[0].lower() not in nested_dict:
        nested_dict[w[0].lower()] = {}
        cnd(w[1:],nested_dict[w[0].lower()])
    else:
        cnd(w[1:],nested_dict[w[0].lower()])
    return


def read_tags(words_dir, nested_dict):
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil in files:
        docID+=1
        with open(fil) as fi:
            for line_number, line in enumerate(fi):
                temp = line.split(',')
#                 print(temp)
                for word in temp:
#                     word = re.sub('[^A-Za-z0-9]+', '', word)
#                     word = re.sub(r'^\s+', ' ',   word)
                    word = word.rstrip()
                    word = word.lstrip()
#                     print(word)
                    cnd(word.lower().split(), nested_dict)
    return docID, tagss

# read the db and creates dictionary
doc_id, tags = read_tags('tags', nested_dict) 


def color_text(word_dict, text, start_index, word):
    i = start_index
    temp_word = word
    if i>=len(text):
        return i, temp_word
#         print(i, ' -> ', text[i:])
    if text[i].lower() in word_dict:
        print(Fore.GREEN + text[i], end = ' ')
        word = word + ' ' + text[i]
#         print(Fore.BLACK + word)
        i, temp_word = color_text(word_dict[text[i].lower()], text, i+1, word)
#         print(Fore.BLACK + temp_word)
    return i, str(temp_word)

def read_jd(words_dir):
    found_words_all = []
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil in files:
        print(fil)
        with open(fil, errors='ignore') as fi:
            found_words = []
            for i, line in enumerate(fi):
                print()
#                 temp = line.split()
                temp = word_tokenize(line)
#                 print((temp))
                j = 0
                while (j < len(temp)):
                    if temp[j].lower() in nested_dict:
                        print(Fore.RED + temp[j] , end = ' ')
                        word = temp[j]
                        temp_word = temp[j]
#                         j, temp_Word = color_text(nested_dict[temp[j].lower()], temp , j+1, word)
                        found_words.append(color_text(nested_dict[temp[j].lower()], temp , j+1, word))
                        j=found_words[-1][0]
#                         print(Fore.RED + i)
                    else:
                        if j<len(temp):
                            print(Fore.BLUE + temp[j], end=' ')
                        j+=1
            
            
            file_name = os.getenv('PATH_PREMIUM_SENTENCE') + str(fil)
#             print(file_name)
            f= open(file_name,"w+", encoding="utf-8")
            for i in found_words:
                for j in i:
                    f.write(j[1])
            f.close()
            
                
            found_words_all.append(found_words)
    return found_words_all

words = read_jd('premium_sentences')


premium_sentences\1.txt

BA/BS degree in Computer Science , related degree or equivalent practical experience . 

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

## 'fil\1.txt'.split('\x0')
# display(words)

In [7]:
# print(nested_dict['data']['scientist'])
display(nested_dict)
# print(stopwords)

{'work': {'autonomously': {}},
 'data': {'scientist': {}, 'modeling': {}, 'structures': {}},
 'gurugram': {},
 'knowledge': {'in': {'business': {'intelligence': {}}}},
 'etl': {'tools': {}},
 'reporting': {'tools': {}},
 'python': {},
 'java': {},
 'scala': {},
 'r': {'language': {}},
 'sql': {},
 'perl': {},
 'pig': {},
 'ml': {},
 'written': {'communication': {'skills': {}}},
 'php': {},
 'mysql': {},
 'affirmative': {'action': {'employer': {}}},
 'gender': {'identity': {}},
 'equal': {'opportunity': {}},
 'sexual': {'orientation': {}},
 'opportunity': {},
 'mohit': {},
 'advisorsjagat': {},
 'jit': {'varish': {'tiwari': {}}}}

In [84]:
def color_text(word_dict, text, start_index, word):
    i = start_index
    temp_word = word
    if i>=len(text):
        return i, temp_word
#         print(i, ' -> ', text[i:])
    if text[i].lower() in word_dict:
        print(Fore.GREEN + text[i], end = ' ')
        word = word + ' ' + text[i]
#         print(Fore.BLACK + word)
        i, temp_word = color_text(word_dict[text[i].lower()], text, i+1, word)
#         print(Fore.BLACK + temp_word)
    return i, str(temp_word)

def read_jd(words_dir):
    found_words_all = []
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil in files:
        docID+=1
        with open(fil, errors='ignore') as fi:
            found_words = []
            for i, line in enumerate(fi):
                print()
#                 temp = line.split()
                temp = word_tokenize(line)
#                 print((temp))
                j = 0
                while (j < len(temp)):
                    if temp[j].lower() in nested_dict:
                        print(Fore.RED + temp[j] , end = ' ')
                        word = temp[j]
                        temp_word = temp[j]
#                         j, temp_Word = color_text(nested_dict[temp[j].lower()], temp , j+1, word)
                        found_words.append(color_text(nested_dict[temp[j].lower()], temp , j+1, word))
                        j=found_words[-1][0]
#                         print(Fore.RED + i)
                    else:
                        if j<len(temp):
                            print(Fore.BLUE + temp[j], end=' ')
                        j+=1
            found_words_all.append(found_words)
    return found_words_all


In [85]:

all_words = read_jd('jd_dir')



Senior Software Engineer , Digital Wealth - Associate 

Job Description : 

BlackRocks Digital Wealth organization is at the center of cutting-edge technologies that serve financial advisors and investors . Digital Wealth consolidates BlackRocks varying products , including iRetire , FutureAdvisor , and Aladdin Risk for Wealth , with marketing and sales teams - with the goal of improving the user experience of its technology products and improving relationships with the advisors who use it . 


This position requires solid hands-on programming , creative problem solving , troubleshooting skills , and an enthusiasm for learning . In this role you will partner with other high-caliber software engineers to enhance and maintain existing and next-generation services and applications . 


Responsibilities : 

Designing , coding , testing , and supporting reliable , robust software applications and services with high-quality standards . 
Participating actively in cross-functional feature req

In [86]:
display(all_words)

[[(10, 'work'),
  (11, 'data structures'),
  (7, 'Equal'),
  (8, 'Equal Opportunity'),
  (12, 'Affirmative Action Employer'),
  (30, 'sexual'),
  (33, 'sexual orientation'),
  (36, 'gender identity')]]

In [87]:

# here i declare a dictionary of words that occur very often but are not stored in the dictionary
non_recognized_words = {}
#  make them as group
from nltk.corpus import stopwords
import string
stop = stopwords.words('english')
punctuations = list(string.punctuation)
stopword = stop + punctuations
type(stopword)


# word = word_tokenize(s)



def clean(line):
    return line.replace("/", " / ")

In [88]:
def stitch(word1, word2):
#     THIS FUNCTION WILL JOIN THE WORD BEFORE TO THE CURRENT WORD TO MAKE A COUPLE
#     THE SAME FUNCTIONALITY CAN BE APPLIED TO WORD DEPTH 3 OR 4 TO INCREASE THE NUMBER OF FEATURES FOR NLP
    if word1 == '':
        return
    return word1+' '+word2

def add_stopword(word, stopword):
    stopword.append(word)

def add_word_to_dictionary(word, tag_directory):
    files = [os.path.join(tag_directory, fi) for fi in os.listdir(tag_directory)]

    # features_matrix = np.zeros((len(files), 3000))
    for fil in files:
        f = open(fil, "a+")
        f.write(word + ', ')
    read_tags('tags', nested_dict)

def test_color_text(word_dict, text, start_index, word):
    i = start_index
    temp_word = word
    if i>=len(text):
        return i, temp_word
#         print(i, ' -> ', text[i:])
    if text[i].lower() in word_dict:
        print(Fore.GREEN + text[i], end = ' ')
        word = word + ' ' + text[i]
#         print(Fore.BLACK + word)
        i, temp_word = test_color_text(word_dict[text[i].lower()], text, i+1, word)
#         print(Fore.BLACK + temp_word)
    return i, str(temp_word)

cw = []
def test_read_jd(words_dir, non_recognized_words, stopwords, nested_dict):
    found_words_all = []
    
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil_num,fil in enumerate(files):
        docID+=1
        with open(fil, errors='ignore') as fi:
            found_words = []
            for i, line in enumerate(fi):
                print()
#                 temp = line.split()
                line = clean(line)
                temp = word_tokenize(line)
#                 print((temp))
                j = 0
                prev = ''
                while (j < len(temp)):
                    if temp[j].lower() in nested_dict:
                        print(Fore.RED + temp[j] , end = ' ')
                        word = temp[j]
                        temp_word = temp[j]
#                         j, temp_Word = color_text(nested_dict[temp[j].lower()], temp , j+1, word)
#                         x = 
                        found_words.append([fil_num, i, color_text(nested_dict[temp[j].lower()], temp , j+1, word)])
                        j=found_words[-1][2][0]
                        prev = ''
#                         print(Fore.RED + i)

#       ------------------------------------------------------------------------------------------
                    elif temp[j].lower() in stopword:
                        prev = ''
                        print(Fore.BLACK + temp[j], end=' ')
                        j+=1
                        continue
#       ------------------------------------------------------------------------------------------          
                    
                    else:
                        if j<len(temp):
                            if temp[j].lower() in non_recognized_words:
                                non_recognized_words[temp[j].lower()] += 1
                            else:
                                non_recognized_words[temp[j].lower()] = 1
#                             for the stitched word
                            if stitch(prev, temp[j]):
                                couple_word = stitch(prev, temp[j])
                                cw.append(couple_word)
                                if couple_word.lower() in non_recognized_words:
                                    non_recognized_words[couple_word.lower()] += 1
                                else:
                                    non_recognized_words[couple_word.lower()] = 1
                            print(Fore.BLUE + temp[j], end=' ')
                            prev = temp[j]
                        j+=1
            found_words_all.append(found_words)
    return found_words_all


In [89]:
test_all_words = test_read_jd('jd_dir', non_recognized_words, stopwords, nested_dict)


Senior Software Engineer , Digital Wealth - Associate 

Job Description : 

BlackRocks Digital Wealth organization is at the center of cutting-edge technologies that serve financial advisors and investors . Digital Wealth consolidates BlackRocks varying products , including iRetire , FutureAdvisor , and Aladdin Risk for Wealth , with marketing and sales teams - with the goal of improving the user experience of its technology products and improving relationships with the advisors who use it . 


This position requires solid hands-on programming , creative problem solving , troubleshooting skills , and an enthusiasm for learning . In this role you will partner with other high-caliber software engineers to enhance and maintain existing and next-generation services and applications . 


Responsibilities : 

Designing , coding , testing , and supporting reliable , robust software applications and services with high-quality standards . 
Participating actively in cross-functional feature req

In [90]:
# non_recognized_words
test_all_words

[[[0, 14, (10, 'work')],
  [0, 24, (11, 'data structures')],
  [0, 31, (8, 'Equal Opportunity')],
  [0, 31, (12, 'Affirmative Action Employer')],
  [0, 33, (8, 'Equal Opportunity')],
  [0, 33, (12, 'Affirmative Action Employer')],
  [0, 33, (30, 'sexual')],
  [0, 33, (33, 'sexual orientation')],
  [0, 33, (36, 'gender identity')]]]

In [91]:
add_word_to_dictionary('mohit', 'tags')

In [92]:
j = 0
q1 = ['knowledge', 'data', ]
word = 'knowledge'
print(color_text(nested_dict[q1[0].lower()], q1 , j+1, word))

(1, 'knowledge')


In [93]:
# print(temp_word)

In [94]:
# extract all the words in a list
we_have = ['work autonomously', 'Data Scientist', 'Gurgaon', 'knowledge in Business Intelligence', 'data modeling', 'ETL', 'reporting tools', 'Python', 'Java', 'Scala', 'R Language']

In [95]:
def hashify(we_have):
    we_want = []
    odds = 3
#     prime numbers will be used in place of odd numbers
    for each in we_have:
        temp = 0
        for alpha in each:
            temp += ord(alpha) * odds
            odds += 2
        print(each, '->', temp)

we_want = hashify(we_have)
    

work autonomously -> 35464
Data Scientist -> 69306
Gurgaon -> 51509
knowledge in Business Intelligence -> 375590
data modeling -> 205353
ETL -> 40089
reporting tools -> 304507
Python -> 137496
Java -> 86554
Scala -> 112846
R Language -> 228490


In [96]:
# for taking in account line number and index of word found and the actual word


def color_text(word_dict, text, start_index, word):
    i = start_index
    temp_word = word
    if i>=len(text):
        return i, temp_word
#         print(i, ' -> ', text[i:])
    if text[i].lower() in word_dict:
        print(Fore.GREEN + text[i], end = ' ')
        word = word + ' ' + text[i]
#         print(Fore.BLACK + word)
        i, temp_word = color_text(word_dict[text[i].lower()], text, i+1, word)
#         print(Fore.BLACK + temp_word)
    return i, str(temp_word)

def read_jd(words_dir):
    found_words_all = []
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil_num,fil in enumerate(files):
        docID+=1
        with open(fil, errors='ignore') as fi:
            found_words = []
            for i, line in enumerate(fi):
                print()
#                 temp = line.split()
                temp = word_tokenize(line)
#                 print((temp))
                j = 0
                while (j < len(temp)):
                    if temp[j].lower() in nested_dict:
                        print(Fore.RED + temp[j] , end = ' ')
                        word = temp[j]
                        temp_word = temp[j]
#                         j, temp_Word = color_text(nested_dict[temp[j].lower()], temp , j+1, word)
#                         x = 
                        found_words.append([fil_num, i, color_text(nested_dict[temp[j].lower()], temp , j+1, word)])
                        j=found_words[-1][2][0]
#                         print(Fore.RED + i)
                    else:
                        if j<len(temp):
                            print(Fore.BLUE + temp[j], end=' ')
                        j+=1
            found_words_all.append(found_words)
    return found_words_all


In [97]:

all_words = read_jd('jd_dir')


Senior Software Engineer , Digital Wealth - Associate 

Job Description : 

BlackRocks Digital Wealth organization is at the center of cutting-edge technologies that serve financial advisors and investors . Digital Wealth consolidates BlackRocks varying products , including iRetire , FutureAdvisor , and Aladdin Risk for Wealth , with marketing and sales teams - with the goal of improving the user experience of its technology products and improving relationships with the advisors who use it . 


This position requires solid hands-on programming , creative problem solving , troubleshooting skills , and an enthusiasm for learning . In this role you will partner with other high-caliber software engineers to enhance and maintain existing and next-generation services and applications . 


Responsibilities : 

Designing , coding , testing , and supporting reliable , robust software applications and services with high-quality standards . 
Participating actively in cross-functional feature req

In [98]:
display(all_words)

[[[0, 14, (10, 'work')],
  [0, 24, (11, 'data structures')],
  [0, 31, (7, 'Equal')],
  [0, 33, (8, 'Equal Opportunity')],
  [0, 33, (12, 'Affirmative Action Employer')],
  [0, 33, (30, 'sexual')],
  [0, 33, (33, 'sexual orientation')],
  [0, 33, (36, 'gender identity')]]]

In [99]:
all_words_dict = {}
def create_all_word_dict(all_words_dict, all_words):
    for i in all_words:
        if len(i)==0:
            continue     
        for j in i:
            if j[0] not in all_words_dict:
                all_words_dict[j[0]] = {}
            if j[2][1].lower() not in all_words_dict[j[0]]:
                all_words_dict[j[0]][j[2][1].lower()] = []
            all_words_dict[j[0]][j[2][1].lower()].append(j[1])
    return all_words_dict    
        
all_words_dict = create_all_word_dict(all_words_dict, all_words)
display(all_words_dict)

{0: {'work': [14],
  'data structures': [24],
  'equal': [31],
  'equal opportunity': [33],
  'affirmative action employer': [33],
  'sexual': [33],
  'sexual orientation': [33],
  'gender identity': [33]}}

In [100]:
# for taking in accout the file number and word index in that file along with the actual word.

def color_text_2(word_dict, text, start_index, word):
    i = start_index
    temp_word = word
    if i>=len(text):
        return i, temp_word
#         print(i, ' -> ', text[i:])
    if text[i].lower() in word_dict:
        print(Fore.GREEN + text[i], end = ' ')
        word = word + ' ' + text[i]
#         print(Fore.BLACK + word)
        i, temp_word = color_text_2(word_dict[text[i].lower()], text, i+1, word)
#         print(Fore.BLACK + temp_word)
    return i, str(temp_word)

def read_jd_2(words_dir):
    found_words_all = []
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]
    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil_num, fil in enumerate(files):
        docID+=1
        with open(fil, errors='ignore') as fi:
            found_words = []
            clean = fi.read().replace('\n', '')

#             for word in clean:
#                 print()
#                 temp = line.split()
            temp = word_tokenize(clean)
#             print((temp))
            j = 0
            while (j < len(temp)):
                if temp[j].lower() in nested_dict:
                    print(Fore.RED + temp[j] , end = ' ')
                    word = temp[j]
                    temp_word = temp[j]
#                         j, temp_Word = color_text(nested_dict[temp[j].lower()], temp , j+1, word)
#                         x = 
#                   MAKING OF ANSWER
                    found_words.append([fil_num,color_text_2(nested_dict[temp[j].lower()], temp , j+1, word)])
                    j=found_words[-1][1][0]
#                         print(Fore.RED + i)
                else:
                    if j<len(temp):
                        print(Fore.BLUE + temp[j], end=' ')
                    j+=1
        found_words_all.append(found_words)
    return found_words_all


In [101]:
words_in_file = read_jd_2('jd_dir')


Senior Software Engineer , Digital Wealth - AssociateJob Description : BlackRocks Digital Wealth organization is at the center of cutting-edge technologies that serve financial advisors and investors . Digital Wealth consolidates BlackRocks varying products , including iRetire , FutureAdvisor , and Aladdin Risk for Wealth , with marketing and sales teams - with the goal of improving the user experience of its technology products and improving relationships with the advisors who use it.This position requires solid hands-on programming , creative problem solving , troubleshooting skills , and an enthusiasm for learning . In this role you will partner with other high-caliber software engineers to enhance and maintain existing and next-generation services and applications.Responsibilities : Designing , coding , testing , and supporting reliable , robust software applications and services with high-quality standards.Participating actively in cross-functional feature requirements gathering ,

In [102]:
display(words_in_file)


[[[0, (152, 'work')],
  [0, (226, 'data structures')],
  [0, (259, 'Equal')],
  [0, (270, 'Equal Opportunity')],
  [0, (274, 'Affirmative Action Employer')],
  [0, (292, 'sexual')],
  [0, (295, 'sexual orientation')],
  [0, (298, 'gender identity')]]]

In [103]:
import numpy as np
import pandas as pd

In [104]:
def fetch_col_for_mat_1(words_dir):
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    tagss = []
    for fil in files:
        with open(fil, errors='ignore') as fi:
            for i, line in enumerate(fi):
                temp = line.split(',')
#                 print(temp)
                for k in temp:
#                     k = re.sub('[^A-Za-z0-9]+', '', k)
#                     k = re.sub(r'^\s+', ' ',   k)
                    k = k.rstrip()
                    k = k.lstrip()
#                     print(k)
                    tagss.append(k)
    return tagss

def fetch_row_for_mat_1(words_dir):
    jd_text = []
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    for fil in files:
        with open(fil, errors='ignore') as fi:
            clean = fi.read().replace('\n', '')
            jd_text.append(clean)
    return jd_text
    
all_cols = fetch_col_for_mat_1('tags')
all_rows = fetch_row_for_mat_1('jd_dir')
# display(len(text1))

def update_matrix_1(df, text, all_rows):
    for key in text:
        if(len(key) == 0):
            continue
        for i in key:
            if i[1][1].lower() in df.columns:
                df.at[all_rows[i[0]], i[1][1].lower()] = 1
#             print(i)
#             print()
    return df


lower_all_cols = []
for i in all_cols:
#     print(type(i))
    lower_all_cols.append(i.lower())

dataFrame1 = np.zeros((len(all_rows), len(lower_all_cols)))
df1 = pd.DataFrame(data = dataFrame1, index = all_rows, columns = lower_all_cols, dtype='int64')
df1[:] = 0



In [105]:
# display(df1)
# print(df1.at[clean,'etl'])
update_matrix_1(df1,words_in_file, all_rows)

work autonomously  \
Senior Software Engineer, Digital Wealth - Asso...                  0   

                                                    data scientist  gurugram  \
Senior Software Engineer, Digital Wealth - Asso...               0         0   

                                                    knowledge in business intelligence  \
Senior Software Engineer, Digital Wealth - Asso...                                   0   

                                                    data modeling  etl  \
Senior Software Engineer, Digital Wealth - Asso...              0    0   

                                                    reporting tools  python  \
Senior Software Engineer, Digital Wealth - Asso...                0       0   

                                                    java  scala  ...  mysql  \
Senior Software Engineer, Digital Wealth - Asso...     0      0  ...      0   

                                                    data structures  \
Senior Software Engineer, Digital Wealth - Asso...                1   

                                                    affirmative action employer  \
Senior Software Engineer, Digital Wealth - Asso...                            1   

                                                    gender identity  \
Senior Software Engineer, Digital Wealth - Asso...                1   

                                                    equal opportunity  \
Senior Software Engineer, Digital Wealth - Asso...                  1   

                                                    sexual orientation  \
Senior Software Engineer, Digital Wealth - Asso...                   1   

                                                    affirmative  opportunity  \
Senior Software Engineer, Digital Wealth - Asso...            0            0   

                                                    mohit     
Senior Software Engineer, Digital Wealth - Asso...      0  0  

[1 rows x 28 columns]

In [106]:
depths = ['same_line', 'A_dist_away', 'B_dist_away', 'C_dist_away']
# 'A' in depths

In [107]:
def matrix_2(lower_all_cols, all_cols, depths):
    word_to_word_dist_mat = np.zeros((len(lower_all_cols), len(lower_all_cols), len(depths)))
    return word_to_word_dist_mat

def fill_matrix_2(lower_all_cols, depths, words_in_file, word_to_word_dist_mat, all_words):
#     THIS LOOP UPDATES THE DEPTH VECTOR IN 3D MATRIX.
    for i in words_in_file:
        if(len(i)==0):
            continue
#         for words i find in each JD, i will calculate the distance of each word from all others in same file.
        index_of_row_word = 0
        index_of_col_word = 0
        for j in i:
            if j[1][1].lower() not in lower_all_cols:
                if j[1][1].lower() not in non_recognized_words:
                    non_recognized_words[j[1][1].lower()] = 1
                else:
                    non_recognized_words[j[1][1].lower()] += 1
            else:
                index_of_row_word = lower_all_cols.index(j[1][1].lower())  
                for k in i:
                    if k==j:
                        continue
                    else:
                        if k[1][1].lower() not in lower_all_cols:
                            continue
                        index_of_col_word = lower_all_cols.index(k[1][1].lower())
                        temp = 0
                        absolute_distance = abs(k[1][0] - j[1][0])
                        if absolute_distance < 7:
                            temp = 1
                        elif absolute_distance < 15:
                            temp = 2
                        else:
                            temp = 3
                        word_to_word_dist_mat[index_of_row_word, index_of_col_word, temp] += 1
#                         a statistical computation is required here
    
#     THIS LOOP WILL UPDATE THE SAME LINE FEATURE AT INDEX 0 IN 3D
    for i in all_words:
        if(len(i)==0):
            continue
#         for words i find in each JD, i will calculate the distance of each word from all others in same file.
        file_num = i[0][0]
        index_of_row_word = 0
        index_of_col_word = 0
        for j in i:
            if j[2][1].lower() not in lower_all_cols:
                continue
            else:
                index_of_row_word = lower_all_cols.index(j[2][1].lower())  
                for k in i:
                    if k==j or k[2][1].lower() not in lower_all_cols:
                        continue
                    else:
                        index_of_col_word = lower_all_cols.index(k[2][1].lower())
                        temp = 0
                        if j[1] == k[1]:
                            word_to_word_dist_mat[index_of_row_word, index_of_col_word, 0] += 1
    
    
    return word_to_word_dist_mat
                        


In [108]:
word_to_word_dist_mat = matrix_2(lower_all_cols, all_cols, depths)
word_to_word_dist_mat = fill_matrix_2(lower_all_cols, depths, words_in_file, word_to_word_dist_mat, all_words)
print(word_to_word_dist_mat)
# print((word_to_word_dist_mat.shape))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  ...
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  ...
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  ...
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 ...

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  ...
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  ...
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  ...
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [109]:
non_recognized_words

{'senior': 1,
 'software': 4,
 'senior software': 1,
 'engineer': 1,
 'software engineer': 1,
 'digital': 3,
 'wealth': 4,
 'digital wealth': 3,
 'associate': 1,
 'job': 1,
 'description': 1,
 'job description': 1,
 'blackrocks': 2,
 'blackrocks digital': 1,
 'organization': 1,
 'wealth organization': 1,
 'center': 1,
 'cutting-edge': 1,
 'technologies': 2,
 'cutting-edge technologies': 1,
 'serve': 1,
 'financial': 1,
 'serve financial': 1,
 'advisors': 2,
 'financial advisors': 1,
 'investors': 1,
 'consolidates': 1,
 'wealth consolidates': 1,
 'consolidates blackrocks': 1,
 'varying': 1,
 'blackrocks varying': 1,
 'products': 2,
 'varying products': 1,
 'including': 2,
 'iretire': 1,
 'including iretire': 1,
 'futureadvisor': 1,
 'aladdin': 1,
 'risk': 1,
 'aladdin risk': 1,
 'marketing': 1,
 'sales': 1,
 'teams': 1,
 'sales teams': 1,
 'goal': 1,
 'improving': 2,
 'user': 1,
 'experience': 5,
 'user experience': 1,
 'technology': 1,
 'technology products': 1,
 'relationships': 1,
 

In [110]:
# SCORING

def matrix_3(lower_all_cols, all_cols):
    word_to_word_scoring_mat = np.zeros((len(lower_all_cols), len(lower_all_cols)))
    return word_to_word_scoring_mat

def fill_matrix_3(word_to_word_dist_mat, word_to_word_scoring_mat):
    for q1,i in enumerate(word_to_word_dist_mat):
#         print(i)
        for q2,j in enumerate(i):
            list_1 = j
            score = list_1[0]*0.5 + list_1[1]*0.25 + list_1[2]*0.15 + list_1[3]*0.05
            word_to_word_scoring_mat[q1][q2] += score
            print(score)
    return word_to_word_scoring_mat



In [111]:
word_to_word_scoring_mat = matrix_3(lower_all_cols, all_cols)
word_to_word_scoring_mat = fill_matrix_3(word_to_word_dist_mat, word_to_word_scoring_mat)
print(word_to_word_scoring_mat)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [34]:
temp_scores = word_to_word_scoring_mat[lower_all_cols.index('php')]



In [35]:
for i,j in enumerate(temp_scores):
    print(lower_all_cols[i], '->', j)

work autonomously -> 0.0
data scientist -> 0.0
gurugram -> 0.0
knowledge in business intelligence -> 0.0
data modeling -> 0.0
etl -> 0.0
reporting tools -> 0.0
python -> 6.699999999999999
java -> 10.0
scala -> 0.0
r language -> 0.0
sql -> 8.35
etl tools -> 0.0
perl -> 1.55
pig -> 0.0
ml -> 0.0
written communication skills -> 0.5
php -> 42.2
mysql -> 45.35
 -> 0.0


In [128]:
from colorama import Fore, Back, Style 
import os
import pickle
import nltk
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
import numpy as np
import pandas as pd
import re
import sys
from nltk.corpus import stopwords
import string
    
# sys.path.append("scr")

# from file import function


''' THE MAIN.PY WILL CALL ALL THE 
    FUNCTIONS THAT ARE PRESENT IN SCR DIRECTORY
    DATA THAT IS PRESENT IN DATA FOLDER '''

# MODULE 1






# MODULE 2

def read_tags_recursive(word_list, nested_dict):
#     print(word_list)
    if(len(word_list) == 0):
        return
    elif word_list[0].lower() not in nested_dict:
        nested_dict[word_list[0].lower()] = {}
        read_tags_recursive(word_list[1:],nested_dict[word_list[0].lower()])
    else:
        read_tags_recursive(word_list[1:],nested_dict[word_list[0].lower()])
    return


def read_tags(words_dir, nested_dict):
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil in files:
        docID+=1
        with open(fil) as fi:
            for line_number, line in enumerate(fi):
                temp = line.split(',')
#                 print(temp)
                for word in temp:
#                     word = re.sub('[^A-Za-z0-9]+', '', word)
#                     word = re.sub(r'^\s+', ' ',   word)
                    word = word.rstrip()
                    word = word.lstrip()
#                     print(word)
                    read_tags_recursive(word.lower().split(), nested_dict)
    return docID, tagss



#######################    MODULE 3
# currently this module return all the words that are matched from the dictionary created in module 2
# adding line number and distance from previous word in the next step...

def clean(line):
    return line.replace("/", " / ")

def stitch(word1, word2):
#     THIS FUNCTION WILL JOIN THE WORD BEFORE TO THE CURRENT WORD TO MAKE A COUPLE
#     THE SAME FUNCTIONALITY CAN BE APPLIED TO WORD DEPTH 3 OR 4 TO INCREASE THE NUMBER OF FEATURES FOR NLP
    if word1 == '':
        return
    return word1+' '+word2

def color_text(word_dict, text, start_index, word):
    index = start_index
    temp_word = word
    if index>=len(text):
        return index, temp_word
#         print(index, ' -> ', text[index:])
    if text[index].lower() in word_dict:
        print(Fore.GREEN + text[index], end = ' ')
        word = word + ' ' + text[index]
#         print(Fore.BLACK + word)
        index, temp_word = color_text(word_dict[text[index].lower()], text, index+1, word)
#         print(Fore.BLACK + temp_word)
    return index, str(temp_word)

def read_jd(words_dir, non_recognized_words, stopword, nested_dict):
    found_words_all = []
    
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil_num,fil in enumerate(files):
        docID+=1
        with open(fil, errors='ignore') as fi:
            found_words = []
            for i, line in enumerate(fi):
                print()
#                 temp = line.split()
                line = clean(line)
                temp = word_tokenize(line)
#                 print((temp))
                j = 0
                prev = ''
                while (j < len(temp)):
                    if temp[j].lower() in nested_dict:
                        print(Fore.RED + temp[j] , end = ' ')
                        word = temp[j]
                        temp_word = temp[j]
#                         j, temp_Word = color_text(nested_dict[temp[j].lower()], temp , j+1, word)
#                         x = 
                        found_words.append([fil_num, i, color_text(nested_dict[temp[j].lower()], temp , j+1, word)])
                        j=found_words[-1][2][0]
                        prev = ''
#                         print(Fore.RED + i)

#       ------------------------------------------------------------------------------------------
                    elif temp[j].lower() in stopword:
                        prev = ''
                        print(Fore.BLACK + temp[j], end=' ')
                        j+=1
                        continue
#       ------------------------------------------------------------------------------------------          
                    
                    else:
                        if j<len(temp):
                            if temp[j].lower() in non_recognized_words:
                                non_recognized_words[temp[j].lower()] += 1
                            else:
                                non_recognized_words[temp[j].lower()] = 1
#                             for the stitched word
                            if stitch(prev, temp[j]):
                                couple_word = stitch(prev, temp[j])
                                # cw.append(couple_word)
                                if couple_word.lower() in non_recognized_words:
                                    non_recognized_words[couple_word.lower()] += 1
                                else:
                                    non_recognized_words[couple_word.lower()] = 1
                            print(Fore.BLUE + temp[j], end=' ')
                            prev = temp[j]
                        j+=1
            found_words_all.append(found_words)
    return found_words_all







def read_jd_2(words_dir, nested_dict):
    found_words_all = []
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil_num, fil in enumerate(files):
        docID+=1
        with open(fil, errors='ignore') as fi:
            found_words = []
            clean = fi.read().replace('\n', '')
            
#             for word in clean:
#                 print()
#                 temp = line.split()
            temp = word_tokenize(clean)
#             print((temp))
            temp_index = 0
            while (temp_index < len(temp)):
                if temp[temp_index].lower() in nested_dict:
                    print(Fore.RED + temp[temp_index] , end = ' ')
                    word = temp[temp_index]
                    temp_word = temp[temp_index]
#                         j, temp_Word = color_text(nested_dict[temp[j].lower()], temp , j+1, word)
#                         x = 
                    found_words.append([fil_num,color_text(nested_dict[temp[temp_index].lower()], temp , temp_index+1, word)])
                    temp_index=found_words[-1][1][0]
#                         print(Fore.RED + i)
                else:
                    if temp_index<len(temp):
                        print(Fore.BLUE + temp[temp_index], end=' ')
                    temp_index+=1
        found_words_all.append(found_words)
    return found_words_all




#  MODULE 4
# df1 is the first matrix
# this first matrix holds rows ad JD's and columns as tags
# value of the matrix is the occurance of that keyword (column heading in the  row (JD)

# this sould be changed to reading from excel sheet or mongoDB
def fetch_col_for_mat_1(words_dir):
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    tagss = []
    for fil in files:
        with open(fil, errors='ignore') as fi:
            for i, line in enumerate(fi):
                words = line.split(',')
#                 print(temp)
                for word in words:
#                     word = re.sub('[^A-Za-z0-9]+', '', word)
#                     word = re.sub(r'^\s+', ' ',   word)
                    word = word.rstrip()
                    word = word.lstrip()
#                     print(word)
                    tagss.append(word)
    return tagss

def fetch_row_for_mat_1(words_dir):
    jd_text = []
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    for fil in files:
        with open(fil, errors='ignore') as fi:
            clean = fi.read().replace('\n', '')
            jd_text.append(clean)
    return jd_text
    


def update_matrix_1(df, text, all_rows):
    for words in text:
        if(len(words) == 0):
            continue
        for word in words:
            if word[1][1].lower() in df.columns:
                df.at[all_rows[word[0]], word[1][1].lower()] = 1
#             print(word)
#             print()
    return df



# MODULE 5

def make_matrix_2(words_dir):
    found_words_all = []
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = {}
    for fil in files:
        docID+=1
        with open(fil, errors='ignore') as fi:
            found_words = []
            # for i, line in enumerate(fi):




#  MODULE 6
#  THE CLUSTER ANALYSIS TO BE THOUGHT UPON

    

# MODULE 7



def matrix_2(lower_all_cols, all_cols, depths):
    word_to_word_dist_mat = np.zeros((len(lower_all_cols), len(lower_all_cols), len(depths)))
    return word_to_word_dist_mat

def fill_matrix_2(lower_all_cols, depths, words_in_file, word_to_word_dist_mat, all_words, non_recognized_words):
#     THIS LOOP UPDATES THE DEPTH VECTOR IN 3D MATRIX.
    for all_words_iterator in words_in_file:
        if(len(all_words_iterator)==0):
            continue
#         for words i find in each JD, i will calculate the distance of each word from all others in same file.
        index_of_row_word = 0
        index_of_col_word = 0
        for word_1 in all_words_iterator:
            if word_1[1][1].lower() not in lower_all_cols:
                if word_1[1][1].lower() not in non_recognized_words:
                    non_recognized_words[word_1[1][1].lower()] = 1
                else:
                    non_recognized_words[word_1[1][1].lower()] += 1
            else:
                index_of_row_word = lower_all_cols.index(word_1[1][1].lower())  
                for word_2 in all_words_iterator:
                    if word_2==word_1:
                        continue
                    else:
                        if word_2[1][1].lower() not in lower_all_cols:
                            continue
                        index_of_col_word = lower_all_cols.index(word_2[1][1].lower())
                        temp = 0
                        absolute_distance = abs(word_2[1][0] - word_1[1][0])
                        if absolute_distance < 7:
                            temp = 1
                        elif absolute_distance < 15:
                            temp = 2
                        else:
                            temp = 3
                        word_to_word_dist_mat[index_of_row_word, index_of_col_word, temp] += 1
#                         a statistical computation is required here
    
#     THIS LOOP WILL UPDATE THE SAME LINE FEATURE AT INDEX 0 IN 3D
    for word_1 in all_words:
        if(len(word_1)==0):
            continue
#         for words i find in each JD, i will calculate the distance of each word from all others in same file.
        file_num = word_1[0][0]
        index_of_row_word = 0
        index_of_col_word = 0
        for word_2 in word_1:
            if word_2[2][1].lower() not in lower_all_cols:
                continue
            else:
                index_of_row_word = lower_all_cols.index(word_2[2][1].lower())  
                for word_3 in word_1:
                    if word_3==word_2 or word_3[2][1].lower() not in lower_all_cols:
                        continue
                    else:
                        index_of_col_word = lower_all_cols.index(word_3[2][1].lower())
                        temp = 0
                        if word_2[1] == word_3[1]:
                            word_to_word_dist_mat[index_of_row_word, index_of_col_word, 0] += 1
    
    
    return word_to_word_dist_mat
                        



# SCORING

def matrix_3(lower_all_cols, all_cols):
    word_to_word_scoring_mat = np.zeros((len(lower_all_cols), len(lower_all_cols)))
    return word_to_word_scoring_mat

def fill_matrix_3(word_to_word_dist_mat, word_to_word_scoring_mat):
    for q1,i in enumerate(word_to_word_dist_mat):
#         print(i)
        for q2,j in enumerate(i):
            list_1 = j
            score = list_1[0]*0.5 + list_1[1]*0.25 + list_1[2]*0.15 + list_1[3]*0.05
            word_to_word_scoring_mat[q1][q2] += score
            # print(score)
    return word_to_word_scoring_mat



def main():

    # here i declare a dictionary of words that occur very often but are not stored in the dictionary
    non_recognized_words = {}
    nested_dict = {}

    stop = stopwords.words('english')
    punctuations = list(string.punctuation)
    stopword = stop + punctuations

    # depths for matrix-2
    depths = ['same_line', 'A_dist_away', 'B_dist_away', 'C_dist_away']	

    # all columns headig in lower case
    lower_all_cols = []

    # read the db and creates dictionary
    doc_id, tags = read_tags('tags', nested_dict)        
    # print(nested_dict)

    all_words = read_jd('jd_dir', non_recognized_words, stopword, nested_dict)
    words_in_file = read_jd_2('jd_dir', nested_dict)

    all_cols = fetch_col_for_mat_1('tags')
    all_rows = fetch_row_for_mat_1('jd_dir')
    # print(len(text1))

    for column_iterator in all_cols:
    #     print(type(i))
        lower_all_cols.append(column_iterator.lower())

    dataFrame1 = np.zeros((len(all_rows), len(lower_all_cols)))
    df1 = pd.DataFrame(data = dataFrame1, index = all_rows, columns = lower_all_cols, dtype='int64')
    df1[:] = 0
    update_matrix_1(df1, words_in_file, all_rows)

    word_to_word_dist_mat = matrix_2(lower_all_cols, all_cols, depths)
    word_to_word_dist_mat = fill_matrix_2(lower_all_cols, depths, words_in_file, word_to_word_dist_mat, all_words, non_recognized_words)
    # print((word_to_word_dist_mat.shape))
    
    with open('all_columns.pkl', 'wb') as f:
        pickle.dump(lower_all_cols, f)


    word_to_word_scoring_mat = matrix_3(lower_all_cols, all_cols)
    word_to_word_scoring_mat = fill_matrix_3(word_to_word_dist_mat, word_to_word_scoring_mat)
    print(word_to_word_scoring_mat)

    with open('scoring_matrix.pkl', 'wb') as f:
        pickle.dump(word_to_word_scoring_mat, f)
    

main()


PHP Developer - MVC / MongoDB / MySQL ( 3-8 yrs ) 

# PHP # MVC # Javascript # MySQL # MongoDB # PostgreSQL 
This opportunity is with a US based product development company setting up its development center in Pune . 

We are primarily looking for candidates with 3-8 years of experience . 

- Strong experience in PHP ( 5.3+ ) , MVC , profiling with x debug , package management . 

- Should have experience working on Javascript , HTML and CSS3 

- Experience on REST Services . 

- Experience working on MySQL / Mongo / Postgres 

Nice to have : 

- Experience working on SAML , OAUTH 
Junior Software Developer ( .NET ) 
Vyvin 
- 
Rohtak , Haryana 
Experience Required 
1-2 Year 

Skills Required 
Good knowledge of Object Oriented Programming concepts . 
Good knowledge of .NET Framework and Microsoft Visual Studio . 
Experience of C # and ASP.NET . 
Good knowlege of HTML , jQuery , and CSS . 
Good verbal and written communication skills . 
Web Developer - PHP ( 2-4 yrs ) 

# Webservices # 

- Actively participate in code reviews to build robust applications and prototypes . 

- Ensure high scalability and performance of the platform . 

- Build proof of concepts and early prototypes systems and scaling it to production . 

- Advocate for good , clean , well-documented and performing code ; define and follow standards and best practices for front-end development . 

We want you if you have : 

- Proven work experience in a product-based company and have experience in both front-end , API and the database / storage layer . 

- Strong skills in Core PHP , MySQL , CSS , HTML5 , jQuery , JavaScript , AJAX , Bootstrap , Web Services , JSON . 

- Strong skills in Python / Golang / Node.Js and experience in API chaining or wrapper development . 

- Experience in building analytics or reporting engines is a plus 

- Integration of user-facing elements developed by front-end developers . 

- Design , code , test , debug and document software according to functional requirements . 


- Solid understanding of OOP , AJAX , jQuery , NodeJS , NoSQL , Server management , Build & Deployment , and MySQL 

Key Requirements : 

Sound knowledge of technologies : Web Technologies like PHP , NodeJS etc and Frontend technologies like Javascript , Angular JS , etc 

- Excellent communication skills 

- Database experience ( MySQL , Memcache , NoSQL ) 

- API fluent ( creation & usage REST prefered ) 

- Working knowledge of source control tools ( git ) 

- Ability to research , learn and implement new technologies in short time 

- Ability to work independently and as part of a team 

- Should have worked in all the stages of SDLC 

- AWS experience is a plus 

Desired Skills and Experience : Strong in Oops concepts and should have worked on any MVC framework ( Laravel preferred ) 


Google Chrome Extension & Google App Script 

Trigent Software Limited 
Delhi ( +1 other ) 
Apply on Monster India 
Apply on Neuvoo 
Over 1 month agoFull–time 
Experience : 1 - 3 years 
Skills : Goo

Working knowledge of SQL Server - writing queries , stored procedures , functions etc . 
Good verbal and written communication skills . 
Desired Experience : 
PHP , MySQL 
Skill Sets : Should have a good communication skills , knowledge in oops concepts PHP and MySQL programming 

Qualifications : Any Degree . 


Please forward your resumes to careers @ bigspire.com and we will get back to you if your resume matches our job criteria . 

Thanks for applying for the job at bigspire 
Job Description Summary : 

PayPal 's Merchant Commerce Solutions Engineering team in Chennai is looking for a talented full-stack engineer to work on the next generation of the Merchant data collection and onboarding applications . We want people who thrive on satisfying the customer and have a passion for creating exceptional user experiences . As a member on our team , you will work directly with our Product Owners and Designers to create outstanding solutions and deliver incredible products . 

We have st

Opportunity : Job Opportunity is provided to well performing interns on internship completion 
Experience : 2 - 50 years 
Skills : Google cloud Platform Engineer|6-9 years|Hyderabad 
Industry : IT / Computers - Software 
Functional Area : IT 

Short Description 
Hiring Google Cloud Platform experience for a banking client . 
We are in urgent need of a candidate who has no more than 60 days notice period and willing to join us at our Cloud Practice ( Will get a good exposure working on Cloud Computing as well ) 
Qualifications 
Qualifications : 
Technical Requirements 
Google Cloud Build and validation 
2 to Years Experience in Google Cloud Platform 
Google Cloud storage , BigQuery , DataProc , DataFlow experience 
Public Cloud exposure 
Excellent written and verbal communication skills 
Desirable Skills 
Cloud experience 
Infrastructure automation experience 
Job Responsibilities 
About the Role / position : Cloud Platform Engineers who are good in Google Cloud Platform service creatio

- A portfolio that reflects your experience and strengths as a designer . 

- Brainstorm new ideas , layouts , and graphics . 

- Positive and enthusiastic with a drive for continuous learning and skill development . 

- Demonstrated compositional and typographical skills . 

- Knowledge of delivery process ( slicing , layering , creating specs ) and a basic knowledge of HTML5 , CSS3 , JavaScript would be a bonus . 
Associate Software Engineer - Digital Wealth 
BlackRock 
375 reviews 
- 
Gurgaon , Haryana 
Description 
About BlackRock 


BlackRock helps investors build better financial futures . As a fiduciary to our clients , we provide the investment and technology solutions they need when planning for their most important goals . As of September 30 , 2018 , the firm managed approximately $ 6.44 trillion in assets on behalf of investors worldwide . For additional information on BlackRock , please visit www.blackrock.com | Twitter : @ blackrock | Blog : www.blackrockblog.com | LinkedI

Ludhiana , Punjab ( Required ) 
Desired Experience : 
Microsoft SQL Server , AJAX , HTML5 , JavaScript , Angular , .Net , T-SQL , OOP 
Job Summary 

Leader Document Processing PVT . LTD.is a company established in 2010 located in Gurgaon . We primarily deal with providing outsourced services to our US based client for various mortgage processing , banking backend work and various software development services for the client 

Description / Job Mission Statement 

We are looking for best of the breed , exceptional talent to work on bleeding edge technology stack , developing next gen financial products . Candidate must have a strong understanding of UI , cross-browser compatibility , general web functions and standards . 

Responsibilities and Duties 

Primarily the role is responsible for designing , coding and modifying websites , from layout to function and according to a product owner specifications . Strive to create visually appealing sites that feature user-friendly design and cl

work : 3 years ( Required ) 
Desired Experience : 
Git , Ant , Java , OOP , REST , Struts 
Job Summary 

Design , build and maintain efficient , reusable , and reliable Java code 
Identify bottlenecks and bugs , and devise solutions to these problems 
Build reusable code and libraries for future use 
Ensure the technical feasibility of Codes 
Optimize application for maximum speed and scalability 
Collaborate with other team members and stakeholders 

Responsibilities and Duties 

Design , build and maintain efficient , reusable , and reliable Java code 
Identify bottlenecks and bugs , and devise solutions to these problems 
Build reusable code and libraries for future use 
Ensure the technical feasibility of Codes 
Optimize application for maximum speed and scalability 
Collaborate with other team members and stakeholders 

Required Experience , Skills and Qualifications 

Proficient in Java , with a good knowledge of its ecosystems 
Solid understanding of object-oriented programming 


Technology Based company 

Visual BI Solutions - PHP Developer - Wordpress / Joomla Framework ( 2-3 yrs ) 

# PHP # Wordpress # Joomla # Drupal # OOAD # Webservices # Open Source # Javascript # jQuery # CMS 
We are looking out for a very creative person who can develop awesome WordPress websites , it would be great if you have experience in developing WordPress Plug-ins & have some experience in Woo-commerce too ! ! ! 

Responsibilities : 

- Develop and manage website and all online properties 

- Write well designed , testable , efficient code by using best software development practices 

- Create site layout / user interface by using standard HTML / CSS practices 

- Integrate data from various back-end services and databases 

- Gather and refine specifications and requirements based on technical needs 

- Be responsible for maintaining , expanding , and scaling our site - Add new features , modify and support existing code and databases for WordPress , Joomla , Drupal and Static

Mentoring junior members of the engineering team on the latest technologies and best practices . 

Qualifications : 

BA / BS in Computer Science or related technical field , or equivalent experience . 
5+ years of professional software development experience in an Agile SDLC . 
3+ years building and supporting high-traffic back-end services 
2+ years of exposure to service-oriented architecture 
A good understanding of object-oriented programming , algorithms , data structures and design patterns . 

Desired Skills : 

1+ years experience with cloud platforms such as Amazon Web Services ( AWS ) . 
Passion for finance and experience in the portfolio management space . 

BlackRock is proud to be an Equal Opportunity / Affirmative Action EmployerM / F / D / V . 


BlackRock is proud to be an Equal Opportunity and Affirmative Action Employer . We evaluate qualified applicants without regard to race , color , national origin , religion , sex , sexual orientation , gender identity , disabil

The successful candidate will be part of the Software Development and Solution test engineering team with the responsibility to work on the development and test strategy , test planning and design of the next generation desktop and web based key software solutions for our clients . 

Responsibilities and Duties 

Key responsibilities will include : 

*Design and develop desktop software or web based solutions ( including portals ) for our esteemed clients . 

*Come up with ideas to develop new software ( desktop / web ) solutions that could bring a valuable change in human lives . 

*Develop and Execute Functional , Interoperability and customer use test cases . 

*Define and qualify End to End / Solution Architectures , engage in debugging complex problems and define solutions . 

*Work on automation , algorithmic thinking and Analytics applications derived from customer use cases . 

*Work on continuous Improvement and Transformation . 

Required Experience , Skills and Qualification

- A product start up candidate who enjoys multi-tasking PHP Developer - MVC/MongoDB/MySQL ( 3-8 yrs ) # PHP # MVC # Javascript # MySQL # MongoDB # PostgreSQLThis opportunity is with a US based product development company setting up its development center in Pune.We are primarily looking for candidates with 3-8 years of experience.- Strong experience in PHP ( 5.3+ ) , MVC , profiling with x debug , package management.- Should have experience working on Javascript , HTML and CSS3- Experience on REST Services.- Experience working on MySQL/Mongo/PostgresNice to have : - Experience working on SAML , OAUTH Junior Software Developer ( .NET ) Vyvin-Rohtak , HaryanaExperience Required1-2 YearSkills RequiredGood knowledge of Object Oriented Programming concepts.Good knowledge of .NET Framework and Microsoft Visual Studio.Experience of C # and ASP.NET.Good knowlege of HTML , jQuery , and CSS.Good verbal and written communication skills . Web Developer - PHP ( 2-4 yrs ) # Webservices # PHP # CRM #

VOCSO Technologies - PHP Developer - Laravel/CodeIgniter Framework ( 0-3 yrs ) # PHP # Laravel # CodeIgniter # CakePHP # Drupal # Wordpress # MVC # Design Patterns- Work experience in frameworks ( Laravel / CodeIgniter /Cake PHP ) .- Work experience In CMS ( Drupal / Wordpress ) will be an added advantage.- Ability to interpret written requirements and technical specification documents.- Proficient understanding of code versioning tools , such as Git.- Understanding of MVC design patterns . Senior Magento Developer - Cloud Services ( 5-10 yrs ) # Magento # Cloud Services # PHP # NopCommerce # Open Source # OpenCart # Data IntegrationFounding Year : 1992Location : Kondapur , HyderabadOffices : USA and IndiaCompany Culture : 6 Days , Flexible shifts - 1st & 3rd Saturdays- are week off- sHeadcount : 150- 200+ Employees and Growing ! ! Job Details : Job Role : Sr. Magento DeveloperSkill : Magento experts who have worked on Cloud platforms , PHPExperience : 6-10 yearsResponsibilities : - De

Wingshield Technologies - PHP Developer - Laravel ( 3-4 yrs ) # PHP # Laravel # MVC # MySQL # OOPS # REST API # jQuery # Javascript # Database Design # AJAXWe have opening for PHP Developer Experience : 3+ yrs exp.Qualification : B.E./B.Tech./MCARole : PHP laravel DeveloperSalary - Till 5 LPA location- Okhla ( New Delhi ) Job Description : Responsibilities : - PHP -Good working knowledge on Core PHP along with MVC Framework Laravel- Strong knowledge of JavaScript , jQuery & Ajax- Knowledge the HTML , CSS , Bootstrap- Strong knowledge of MySQL databases & OOPS concepts- Strong knowledge of Laravel.- Strong knowledge of Rest APIs- Integration of user-facing elements developed by front-end developers - Solve complex performance problems and architectural challenges - Write well designed , testable , efficient code by using best software development practices - Integrate data from various back-end services and databases ( third party plug-in integration ) - Gather and refine customer requi

Job PositionTrainee Software Application Support Analyst - Mangalore BranchJob DetailsResponsible for providing support to USA/ Canada clients via phone , online chat & e-mail , troubleshooting issues reported by clients , supplemental QA activities , ensuring maximum customer satisfaction . Knowledge of networking concepts & MS SQL Server will be a plus.RequirementsMust be willing to work in permanent NightshiftShould have excellent communication skills ( both Verbal & Written ) Exceptionally sharp fresher ’ s can applyEstablishing a cordial relationship with the clients so as to ensure maximum customer satisfactionShould have exposure interacting with USA clients ( Voice Process ) Job CodeTrainee Application Support AnalystExperienceAny graduate fresher 2016/2017 passed out ITH Technologies - MEAN Stack Developer - Full Stack ( 1-8 yrs ) # MEAN # Full Stack # AngularJS # Node.js # MongoDB # Express.js # PHP # Open SourceWe are looking for a skilled Mean Stack Developer who will be re

Junior Software Developer ( SQL Server ) Vyvin-Rohtak , HaryanaExperience Required1-2 YearSkills RequiredGood knowledge of Relation Database concepts.Working knowledge of SQL Server - writing queries , stored procedures , functions etc.Good verbal and written communication skills . Sr. Software DeveloperICON SOFTWARE TECHNOLOGIES-Ludhiana , Punjab ? 25,000 - ? 38,000 a monthRequired Experience , Skills and QualificationsTechnology : - C # , ASP.NET/MVC- , SQL server ) .Qualification : Btech/MCA/ BCA or equivalentAddress : Icon Software Technologies , Onkar Vihar , Opp Sector 32-A , Ludhiana , Punjab.Job Type : Full-timeSalary : ? 25,000.00 to ? 38,000.00 /monthExperience : dot net : 1 year ( Required ) Education : Bachelor 's ( Required ) Location : Ludhiana , Punjab ( Required ) Desired Experience : Microsoft SQL Server , AJAX , HTML5 , JavaScript , Angular , .Net , T-SQL , OOPJob SummaryLeader Document Processing PVT . LTD.is a company established in 2010 located in Gurgaon . We prim

SOFTWARE ENGINEERHCL Technologies7,658 reviews-Noida , Uttar PradeshJob Description To resolve the tickets raised as per the defined standards of time| cost and quality for increased customer satisfaction . ( 1 . ) To document all the defined processes and the methods of resolving the ticket| troubleshooting| etc . ( 2 . ) To interface with customers for ticket clarification/resolution ( 3 . ) To troubleshoot and resolve tickets raised by the clients . ( 4 . ) To update self on latest technologies and related areas Qualification B Tech Skill ( Primary ) Technical Skills-ERP Peoplesoft Technical-Reporting Desired Experience : Hibernate , Node.js , Git , HTML5 , MySQL , Java , Service-Oriented Architecture , JSP , Maven , JSON , REST , Backbone.jsJob SummaryTPConnects is looking for JAVA / J2EE with Travel Technology Experienced Software Engineers to be based in Dubai Office.Minimum 6-9 year experience with BTech/BE with airlines or travel technology background.Experience in Server Side 

Job Description Send me Jobs like thisPrestigious MNC is expanding its operations in India working on development of cloud-based platform-stream processing , large-scale distributed applicationsMUST3+ years of experience in .NET server-side development2+ years in Python developmentSalary : INR 7,00,000 - 17,00,000 P.A.Industry : IT-Software / Software ServicesFunctional Area : IT Software - Application Programming , MaintenanceRole Category : Programming & DesignRole : Software DeveloperEmployment Type : Permanent Job , Full TimeKeyskillssoftware development .net architecture database design database designer software architecture design python development soap AWS VCS - GITDesired Candidate ProfileServer-side development , RDBMS-backend applications & SOAP/REST web servicesExperienced with .NET Core , version control using Git & development with AWS servicesGood verbal & written communication skillsSelf-driven , quick learner with eye to detailEducation-UG : BCA - Computers , Any Grad

continuous Improvement and Transformation.Required Experience , Skills and Qualifications*Deeply passionate about quality and customer success . *Solid working knowledge of C , C++ , .NET ( C # or VB.NET ) , ASP.NET , Python and PHP . *Working knowledge on Integration of backend Databases and different Data Models is a must . *Dynamic experience in Software Quality Assurance with an incredible appetite to make products / solutions better . *Automation experience with Python , REST , Jenkins & Strong Linux fundamentals . *Strong written & verbal communication , and interpersonal skills.Results oriented with a high degree of accountability , dedication and responsibility. -- Qualifications and Requirements : *BS/MS degree or equivalent in a relevant technical discipline such as EE/CS/ET combined with 2-3+ years of related experience in software ( desktop and web ) development and software testing experience . *Excellent problem-solving skills , familiarity with Linux and modern software 

[[ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 

In [129]:
import heapq
import numpy

with open('all_columns.pkl', 'rb') as f:
    all_columns = pickle.load(f)

with open('scoring_matrix.pkl', 'rb') as f:
    scoring_matrix = pickle.load(f)
    
input_word = 'equal opportunity'

index = all_columns.index(input_word)

for i, j in enumerate(all_columns):
    print(j, ' <-> ', scoring_matrix[index][i])
#     print(type(scoring_matrix[index]))


ans = heapq.nlargest(5, range(len(scoring_matrix[index])), scoring_matrix[index].take)    
for i in ans:
    print(all_columns[i])

# dataFrame2 = np.zeros((len(all_columns), len(all_columns)))
dataFrame2 = np.asmatrix(scoring_matrix)
df2 = pd.DataFrame(data = dataFrame2, index = all_columns, columns = all_columns, dtype='float64')
display(df2)

work autonomously  <->  0.0
data scientist  <->  0.0
gurugram  <->  0.0
knowledge in business intelligence  <->  0.0
data modeling  <->  0.0
etl  <->  0.0
reporting tools  <->  0.0
python  <->  0.0
java  <->  0.0
scala  <->  0.0
r language  <->  0.0
sql  <->  0.0
etl tools  <->  0.0
perl  <->  0.0
pig  <->  0.0
ml  <->  0.0
written communication skills  <->  0.0
php  <->  0.0
mysql  <->  0.0
data structures  <->  0.15000000000000002
affirmative action employer  <->  2.35
gender identity  <->  1.75
equal opportunity  <->  0.1
sexual orientation  <->  1.75
affirmative  <->  0.0
opportunity  <->  0.0
mohit  <->  0.0
  <->  0.0
affirmative action employer
gender identity
sexual orientation
data structures
equal opportunity


work autonomously  data scientist  \
work autonomously                                 0.0             0.0   
data scientist                                    0.0             0.0   
gurugram                                          0.0             0.0   
knowledge in business intelligence                0.0             0.0   
data modeling                                     0.0             0.0   
etl                                               0.0             0.0   
reporting tools                                   0.0             0.0   
python                                            0.0             0.0   
java                                              0.0             0.0   
scala                                             0.0             0.0   
r language                                        0.0             0.0   
sql                                               0.0             0.0   
etl tools                                         0.0             0.0   
perl                                              0.0             0.0   
pig                                               0.0             0.0   
ml                                                0.0             0.0   
written communication skills                      0.0             0.0   
php                                               0.0             0.0   
mysql                                             0.0             0.0   
data structures                                   0.0             0.0   
affirmative action employer                       0.0             0.0   
gender identity                                   0.0             0.0   
equal opportunity                                 0.0             0.0   
sexual orientation                                0.0             0.0   
affirmative                                       0.0             0.0   
opportunity                                       0.0             0.0   
mohit                                             0.0             0.0   
                                                  0.0             0.0   

                                    gurugram  \
work autonomously                        0.0   
data scientist                           0.0   
gurugram                                 0.0   
knowledge in business intelligence       0.0   
data modeling                            0.0   
etl                                      0.0   
reporting tools                          0.0   
python                                   0.0   
java                                     0.0   
scala                                    0.0   
r language                               0.0   
sql                                      0.0   
etl tools                                0.0   
perl                                     0.0   
pig                                      0.0   
ml                                       0.0   
written communication skills             0.0   
php                                      0.0   
mysql                                    0.0   
data structures                          0.0   
affirmative action employer              0.0   
gender identity                          0.0   
equal opportunity                        0.0   
sexual orientation                       0.0   
affirmative                              0.0   
opportunity                              0.0   
mohit                                    0.0   
                                         0.0   

                                    knowledge in business intelligence  \
work autonomously                                                  0.0   
data scientist                                                     0.0   
gurugram                                                           0.0   
knowledge in business intelligence                                 0.0   
data modeling                                                      0.0   
etl                                                                0.0   
reporti